# Generated by Django 4.2.1 on 2023-05-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Ethaddress',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='Ethprivatekey',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
